# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'sameersalunke/bootcamp-demo:$(build.buildId)'

steps: 
- task: Docker@1
  displayName: Container registry login
  inputs:
    command: login
    azureSubscriptionEndpoint: AzureDevCampDemo
    azureContainerRegistry: igdevcampdemo.azurecr.io
- script: docker build -t igdevcampdemo.azurecr.io/$(imageName) ./app 
- script: docker push igdevcampdemo.azurecr.io/$(imageName)

   